/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest4;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Rayzal
 */
public class customerForm extends javax.swing.JFrame {

    /**
     * Creates new form customerForm
     */
    public customerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JNama = new javax.swing.JTextField();
        jNTelepon = new javax.swing.JTextField();
        jberat1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        sliderValue2 = new javax.swing.JLabel();
        sliderValue3 = new javax.swing.JLabel();
        sliderValue = new javax.swing.JLabel();
        sliderValue1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jReguler = new javax.swing.JRadioButton();
        jExpress = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jProses = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        juLANG = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Customer Form");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("No. Telepon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Berat Barang");

        JNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JNamaKeyTyped(evt);
            }
        });

        jNTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNTeleponKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNTeleponKeyTyped(evt);
            }
        });

        jberat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jberat1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jberat1KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("KG");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jNTelepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(JNama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jberat1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel5))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jberat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Atur Diskon");

        jSlider3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSlider3MouseMoved(evt);
            }
        });

        sliderValue2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sliderValue2.setText("0");

        sliderValue3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sliderValue3.setText("100");

        sliderValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sliderValue.setText("0");

        sliderValue1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sliderValue1.setText("%");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jenis Jasa");

        buttonGroup1.add(jReguler);
        jReguler.setText("Reguler");

        buttonGroup1.add(jExpress);
        jExpress.setText("Express");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Total Harga");

        jHarga.setEditable(false);
        jHarga.setBackground(new java.awt.Color(51, 51, 51));
        jHarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jHarga.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jReguler)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jExpress))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sliderValue2)
                        .addGap(79, 79, 79)
                        .addComponent(sliderValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderValue1))
                    .addComponent(sliderValue3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jHarga))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderValue2)
                    .addComponent(sliderValue)
                    .addComponent(sliderValue1)
                    .addComponent(sliderValue3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReguler)
                    .addComponent(jExpress))
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(102, 255, 0));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));

        jProses.setText("PROSES");
        jProses.setEnabled(false);
        jProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProsesActionPerformed(evt);
            }
        });

        jbKeluar.setText("KELUAR");
        jbKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbKeluarMouseClicked(evt);
            }
        });
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });

        juLANG.setText("ULANG");
        juLANG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juLANGMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juLANG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbKeluar)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKeluar)
                    .addComponent(juLANG)
                    .addComponent(jProses))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbKeluarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbKeluarMouseClicked

   
    private void jSlider3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseMoved
        // TODO add your handling code here:
       sliderValue.setText(String.valueOf(jSlider3.getValue()));
        
    }//GEN-LAST:event_jSlider3MouseMoved

    private void juLANGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juLANGMousePressed
        // TODO add your handling code here:
        JNama.setText(" ");
        jHarga.setText(" ");
        jNTelepon.setText(" ");
        jberat1.setText(" ");
          
    }//GEN-LAST:event_juLANGMousePressed

    private void jProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProsesActionPerformed
        // TODO add your handling code here:
        
        float diskon, totalDiskon, totalharga, seluruh;
        //berat barang
        String berat = jberat1.getText();
        int beratBR = Integer.parseInt(berat);
        //jslider diskon
        diskon = jSlider3.getValue();
   
        if (JNama.getText().length() == 0) {
                JOptionPane.showMessageDialog(rootPane,"Isi  Nama terlebih dahulu");
                JNama.requestFocus();   
            } else   if (jNTelepon.getText().length() == 0) {
                JOptionPane.showMessageDialog(rootPane,"Isi  No telpon terlebih dahulu");
                jNTelepon.requestFocus();
            } else   if (jberat1.getText().length() == 0 ) {
                JOptionPane.showMessageDialog(rootPane,"Isi Berat Barang terlebih dahulu");
                jNTelepon.requestFocus();
            }else  if (!jReguler.isSelected() &&  !jExpress.isSelected()) {
                 JOptionPane.showMessageDialog(rootPane,"Pilih jenis jasa terlebih dahulu");
                 jProses.requestFocus();
                  }else  if (beratBR == 0) {
                 JOptionPane.showMessageDialog(rootPane,"Berat Barang tidak boleh nol (0)");
                 jProses.requestFocus();
                  }

        
        if (jReguler.isSelected()) {      
        totalharga = (11500* beratBR);
        totalDiskon =  totalharga*(diskon/100);
        seluruh =  totalharga - totalDiskon;
        jHarga.setText("Rp.  "+seluruh);
        } else if(jExpress.isSelected()){
        totalharga = (float) ((11500* beratBR)*1.5);
        totalDiskon =  totalharga*(diskon/100);
        seluruh =  totalharga - totalDiskon;
        jHarga.setText("Rp.  "+seluruh);
        }     
   
    }//GEN-LAST:event_jProsesActionPerformed

    private void JNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JNamaKeyPressed
        // TODO add your handling code here:
              if (evt.getKeyCode() == evt.VK_ENTER)
        {
           if (JNama.getText() .length() == 0)
           {
               JOptionPane.showMessageDialog(null,"Nama tidak boleh Kosong"," Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
               JNama.requestFocus();
               return;
           }
           jProses.requestFocus();
        }
    }//GEN-LAST:event_JNamaKeyPressed

    private void jNTeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNTeleponKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == evt.VK_ENTER)
        {
           if (jNTelepon.getText() .length() == 0)
           {
               JOptionPane.showMessageDialog(null,"Nomor Telepon tidak boleh Kosong"," Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
               jNTelepon.requestFocus();
               return;
           }
           jProses.requestFocus();
        }
    }//GEN-LAST:event_jNTeleponKeyPressed

    private void jberat1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jberat1KeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == evt.VK_ENTER)
        {
           if (jberat1.getText() .length() == 0)
           {
               JOptionPane.showMessageDialog(null,"Berat Barang  tidak boleh Kosong"," Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
               jberat1.requestFocus();
               return;
           }
             jProses.requestFocus();
    }//GEN-LAST:event_jberat1KeyPressed
    }
    
    //AGAR INPUTAN NO TELEPON HANYA ANGKA
    private void jNTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNTeleponKeyTyped
        // TODO add your handling code here:
               if (JNama.getText().length()>0&&jNTelepon.getText().length()>0&&jberat1.getText().length()>0){
               jProses.setEnabled(true); }
        else {
               jProses.setEnabled(false); }
        char karakter = evt.getKeyChar();
     if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            JOptionPane.showMessageDialog(null, "masukan hanya angka saja");
    getToolkit().beep();
    evt.consume();
       }

    }//GEN-LAST:event_jNTeleponKeyTyped
 //AGAR INPUTAN BERAT BARANG HANYA ANGKA
    private void jberat1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jberat1KeyTyped
        // TODO add your handling code here:
             if (JNama.getText().length()>0&&jNTelepon.getText().length()>0&&jberat1.getText().length()>0){
               jProses.setEnabled(true); }
        else {
               jProses.setEnabled(false); }
               char karakter = evt.getKeyChar();
     if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
         JOptionPane.showMessageDialog(null, "masukan hanya angka saja");
    getToolkit().beep();
    evt.consume();
       }
  
    
    }//GEN-LAST:event_jberat1KeyTyped

    private void JNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JNamaKeyTyped
        // TODO add your handling code here:
        if (JNama.getText().length()>0&&jNTelepon.getText().length()>0&&jberat1.getText().length()>0){
               jProses.setEnabled(true); }
        else {
               jProses.setEnabled(false); }
    }//GEN-LAST:event_JNamaKeyTyped

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
                System.exit(0);
    }//GEN-LAST:event_jbKeluarActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JNama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jExpress;
    private javax.swing.JTextField jHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNTelepon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jProses;
    private javax.swing.JRadioButton jReguler;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JTextField jberat1;
    private javax.swing.JButton juLANG;
    private javax.swing.JLabel sliderValue;
    private javax.swing.JLabel sliderValue1;
    private javax.swing.JLabel sliderValue2;
    private javax.swing.JLabel sliderValue3;
    // End of variables declaration//GEN-END:variables
}
